# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

# Language and response settings
language: "ja-JP" # CodeRabbitのレビューコメントを日本語で生成

# Tone of review comments
tone_instructions: "日本語で丁寧にレビューしてください。建設的で具体的なフィードバックを提供し、コードの改善点を明確に説明してください。"

# Chat settings
chat:
  # Auto-reply to comments
  auto_reply: true

# Early access and tier settings
early_access: true
enable_free_tier: true

# Review settings
reviews:
  # Approve the review once CodeRabbit’s comments are resolved and no pre-merge checks are in an error state.
  # Note: In GitLab, all discussions must be resolved.
  request_changes_workflow: true

  # High level summary
  high_level_summary: true

  # Poem generation for PR summaries
  poem: false

  # Review status comment
  review_status: true

  # Generate walkthrough in a markdown collapsible section.
  collapse_walkthrough: true

  # Tools and checks
  tools:
    # GitHub Checks integration
    github-checks:
      enabled: true
      timeout_ms: 90000
    # PHPStan is a tool to analyze PHP code.
    phpstan:
      enabled: true
      level: default
    # PHPMD is a tool to find potential problems in PHP code.
    phpmd:
      enabled: true
    # PHP CodeSniffer is a PHP linter and coding standard checker.
    phpcs:
      enabled: true

  # Auto-review settings
  auto_review:
    enabled: true # Automatically review all PRs

    # Ignore certain file patterns
    ignore_title_keywords:
      - "WIP"
      - "DO NOT REVIEW"

    drafts: false # Don't review draft PRs

    base_branches:
      - main
      - master
      - develop

  # Path filters - exclude unnecessary directories
  path_filters:
    - "!vendor/**"
    - "!.git/**"
    - "!.github/**"

  # Path-based instructions for specific areas
  path_instructions:
    - path: "src/**/*.php"
      instructions: |
        - PHP 8.4+の機能を活用しているか確認
        - セキュリティ脆弱性（SQLインジェクション、XSS、コマンドインジェクション等）をチェック
        - PSR-12コーディング規約に準拠しているか確認
        - エラーハンドリングが適切か確認
        - 型宣言とdocblockが適切か確認

    - path: "tests/**/*.php"
      instructions: |
        - テストが実際にコードの動作を検証しているか確認
        - エッジケースがカバーされているか確認
        - モックが適切に使用されているか確認
        - アサーションが明確で意味のあるメッセージを持っているか確認
        - 重複テストがないか確認
